### ISSUE TITLE
"RGB curves" in compositing

### ISSUE THREAD

**Issue by valiGrimO** [valiGrimO/PETrA#2]
In fact, there is one kind of node in compositing I didn't succeed to configure : RGB curves...
I skipped it from my minds, I was so happy with color ramps!

https://github.com/valiGrimO/PETrA/blob/16b20fad8b737b3b2b5fc44c440ddaac4b247cb7/scripts/petra_blender_addon/setup/compositing.py#L178

**Comment by mikez** [comment]
`nodeH3e.mapping.curves[3].points.new(0.5, 0.5)`

Change `curves[3]` to e.g. `curves[1]` to get another of the CRGB curves.

See more here: https://docs.blender.org/api/current/bpy.types.CurveMapPoints.html

**Comment by valiGrimO** [comment]
I feel dumm... I searched actively the solution with the python console and on the Blender Documentation, but I can't find out how to change the position of a point, nor to remove a point to let only the points with the right position :/

https://github.com/valiGrimO/PETrA/blob/2ecd9f53bf2cc6c57785b66c96770fe45b4d5948/scripts/petra_blender_addon/setup/compositing.py#L474

**Comment by mikez** [comment]
I'm certain it will become easier, once you've done this documentation searching a couple of times. :)

1. Change position:
```python
nodeB2c.mapping.curves[3].points[0].location
```

you can find this out, by looking up the documentation for [CurveMapPoint](https://docs.blender.org/api/current/bpy.types.CurveMapPoint.html#bpy.types.CurveMapPoint) or doing `dir(nodeB2c.mapping.curves[3].points[0])`.


2. Remove point:
```python
>>> p = nodeB2c.mapping.curves[3].points[1]
>>> nodeB2c.mapping.curves[3].points.remove(p)
```

**Comment by valiGrimO** [comment]
I was very close to change the position in fact!
Now, the compositing script is fully operationnal :+1:
