### ISSUE TITLE
control orthographic scale of cameras through the size of framing box

### ISSUE THREAD

**Issue by valiGrimO** [valiGrimO/PETrA#3]
https://github.com/valiGrimO/PETrA/blob/eb4fdd64571490eb0a91446310641115fca27075/scripts/petra_blender_addon/setup/initial.py#L111

I tried with something like that:

> # get reference
> sX = bpy.data.objects["Framing Box"].scale[0]
> sY = bpy.data.objects["Framing Box"].scale[1]
> sZ = bpy.data.objects["Framing Box"].scale[2]

> # get the highest value for Cam-01 and 03
> orthoScaleA = max(sX, sZ) # relevant for Cam-01 and Cam-03
> orthoScaleB = max(sY, sZ) # relevant for Cam-02 and Cam-04
> orthoScaleC = max(sX, sY) # relevant for Cam-05 and Cam-06

and then... then it's absolutly not that, I get confused... :(
> # 
> bpy.data.objects["Framing Box"].driver_add("orthoScaleA", 1)
> bpy.data.objects["Cam-01"].driver_paste("Camera.ortho_scale")

You will find [here an example of how drivers are affecting orthographic scale of cameras](https://github.com/valiGrimO/PETrA/blob/eb4fdd64571490eb0a91446310641115fca27075/scripts/petra_blender_addon/setup/initial_orthoScale_driverExample.blend) (for Cam-01, play with dimensions X  and Y of framing box):

**Comment by mikez** [comment]
Check the answers here: https://blender.stackexchange.com/q/58886
Especially the second one looks relevant here. It does not use `max` of Python.

**Comment by valiGrimO** [comment]
I try to isolate the problem, but... it's too hard for me :/
I feel like when the script will work on this plane, I will adapt it easily to the cube.
I am definitly not good to understand what is under the hood of Python!

https://github.com/valiGrimO/PETrA/blob/f36c68d24298f69a69429bf51698dc1e76d847f8/scripts/petra_blender_addon/setup/cameraConstraintSimple.py

**Comment by mikez** [comment]
## Create new drivers
```python
>>> camera = bpy.data.objects["Cam-01"].data
>>> framing_box = bpy.data.objects["Framing Box"]
>>> fcurve = camera.driver_add("ortho_scale")
>>> fcurve.driver.type = "MAX"

>>> var1 = fcurve.driver.variables.new()
>>> var1.targets[0].id = framing_box
>>> var1.targets[0].data_path = "dimensions[0]"

>>> var2 = fcurve.driver.variables.new()
>>> var2.targets[0].id = framing_box
>>> var2.targets[0].data_path = "dimensions[2]"
```

## Inspect created drivers

```python
>>> camera = bpy.data.objects["Cam-01"].data
>>> drivers = camera.animation_data.drivers

>>> drivers[0].data_path
'ortho_scale'
>>> drivers[0].driver.type
'MAX'

>>> drivers[0].driver.variables[0].targets[0].id
bpy.data.objects['Framing Box']
>>> drivers[0].driver.variables[0].targets[0].data_path
'dimensions[0]'

>>> drivers[0].driver.variables[1].targets[0].id
bpy.data.objects['Framing Box']
>>> drivers[0].driver.variables[1].targets[0].data_path
'dimensions[2]'
```

**Comment by valiGrimO** [comment]
There is an error when I execute the script line 139 
https://github.com/valiGrimO/PETrA/blob/5b69097f3bebf062e3a35e6ecdf80ea3ee4c7bdb/scripts/petra_blender_addon/setup/initial.py#L139
I also noticed 2 open quotes at the end of lines (I removed them):
bpy.data.objects['Framing Box']"

**Comment by mikez** [comment]
@valiGrimO Oh, let me clarify:

- Create new drivers: this goes into the Python script.
- Inspect created drivers: this is for you to try out in the Interactive Blender Python Console.
- The lines that start with '>>>' are commands. The lines without '>>>' are the result from that command. They should not be included.

The idea was for you to play around with this in the Blender Python Console to understand. :)

**Comment by mikez** [comment]
I also corrected two mistakes. :) 🙏

**Comment by valiGrimO** [comment]
Oh... sorry, I didn't get it!
It was too subtle for my mind! 😅
