### ISSUE TITLE
call node groups

### ISSUE THREAD

**Issue by valiGrimO** [valiGrimO/PETrA#4]
I don't know how to call node groups I created in composting.py 

https://github.com/valiGrimO/PETrA/blob/9e0b73455a0fe326c16191ebc3ebd7bc74d12e4b/scripts/petra_blender_addon/renderLayers/layer_C1_PRV.py#L9

**Comment by mikez** [comment]
`node2.nodes["Group Input"]`

you can inspect with

```python
>>> node2.nodes.keys()
>>> dir(node2)
```

**Comment by valiGrimO** [comment]
ouch... I still don't get it :/
What should I write in order to make the first connection possible, line 33?
I inspected with `.keys()` and `dir()`, but I don't really understand what I should do with what comes from the console...

https://github.com/valiGrimO/PETrA/blob/d2a721957ef1d781165fcd2609fc358a1764b1ac/scripts/petra_blender_addon/renderLayers/layer_C1_PRV.py#L33

**Comment by mikez** [comment]
@valiGrimO I think there's a conceptual misunderstanding. And now I understand what your question is. You **don't** want node groups, you want nodes.

```python
node1 = bpy.data.scenes["Scene"].node_tree.nodes["Render Layers"]
```

This is correct. You are getting the node with the name "Render Layers" from the outmost node tree.

```python
node2 = bpy.data.node_groups["Hub"]
```

This is incorrect. You are getting a generic node group with the name "Hub". This group might be used for many different nodes. What you actually want is the unique name of the Node in the outermost layer; not the group name.

![image](https://user-images.githubusercontent.com/216956/127639371-402e4c3e-47f0-4880-bc59-f3d9a9b5833d.png)

For example:

```python
node2 = bpy.data.scenes["Scene"].node_tree.nodes["Group"]
```

I believe the name "Group" was automatically assigned. You can also give another name in the compositor script.

**Comment by mikez** [comment]
One more example to demonstrate.

Here are three nodes. All have different names: "Group", "Group.007", "Group.008". However, they all have the **same** node group called Hub. So if you modify Hub, it will modify it for all. They're all using the same node group.

![image](https://user-images.githubusercontent.com/216956/127640190-eca7001d-1049-4c0d-8cb3-d1089c1f6671.png)
