### ISSUE TITLE
Compute render size of each camera

### ISSUE THREAD

**Issue by valiGrimO** [valiGrimO/PETrA#6]
_**not really an issue, more a request :)**_

In the "camera setup" section, we define the documentation's scale (`DS`) and the spatial resolution (`SR`). This affect directly the size of the render (in pixels).

Inputs:
+ `DS` = Documentation's Scale
+ `SR` = Spatial Resolution

Those 2 inputs allows to compute the resolution of images (`RI`, in ppi):
`RI = ROUND(DS/(SR/25.4))`

To compute the render size (in pixels), we have to start from the size of the framing box.
`scale[0] = U1`
`scale[1] = U2`
`scale[2] = U3`

Each predefined camera are defined as follow (in meters):
`Cam-01 = U1, W1`
`Cam-02 = V1, W1`
`Cam-03 = U1, W1`
`Cam-04 = V1, W1`
`Cam-05 = U1, V1`
`Cam-06 = U1, V1`

This help to define the size of the printed images (you know already it for the layout part):
`U2 = ROUND(U1/DS*100;2)`
`V2 = ROUND(V1/DS*100;2)`
`W2 = ROUND(W1/DS*100;2)`

**And here we get the size of the pictures in pixels:**
`U3 = ROUND(1/(2.54/RI)*U2)`
`V3 = ROUND(1/(2.54/RI)*V2)`
`W3 = ROUND(1/(2.54/RI)*W2)`

So each predefined camera are defined as follow (in pixels):
`Cam-01 = U3, W3`
`Cam-02 = V3, W3`
`Cam-03 = U3, W3`
`Cam-04 = V3, W3`
`Cam-05 = U3, V3`
`Cam-06 = U3, V3`

When we click on the "apply" button, those values should fill the `render.resolution_x` and `render.resolution_y` :)

**Comment by mikez** [comment]
I uploaded the button.

However, the button applies the selected camera to the entire scene, because `render.resolution_x` applies for the **entire scene**, not an individual camera.

**Comment by mikez** [comment]
BTW. I also corrected several formulas which appeared to be wrong.
